language: python
python:
  - 3.8
dist: focal
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install coverage
  - pip install pytest-cov
install:
  - pip install . # install package
script: pytest -v # run tests
after_success:
  - codecov # submit coverage

