language: python
python:
  - 3.8
dist: focal
branches:
  only:
  - main
before_install:
  - python --version
  - pip install pytest pytest-cov codecov
install:
  - pip install .
script: pytest -v --cov-report term-missing --cov=critter tests/
after_success:
  - codecov

