language: python
python:
  - 3.8
dist: focal
branches:
  only:
  - main
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install coverage
  - pip install pytest-cov
install:
  - pip install .
script: pytest -v --cov-report term --cov=critter --ignore=critter/version.py --ignore=critter/terminal.py tests/
after_success:
  - codecov

